export const products = [
    {
      id: 1,
      title: "Days Gone",
      image: "https://as.com/meristation/imagenes/2020/11/03/game_cover/666031971604438123.jpg",
      price: 11200,
      descripcion: "Days Gone es un videojuego de terror y acción-aventura, desarrollado por el estudio SIE Bend Studio y publicado por Sony Interactive Entertainment para PlayStation 4 y Microsoft Windows. Fue lanzado en PlayStation 4 el 26 de abril del año 2019 y el 18 de mayo de 2021 para Microsoft Windows.",
      stock: 5,
      category: "accion",
    },
    {
      id: 2,
      title: "Call of Duty",
      image: "https://es.keysoff.com/media/catalog/product/cache/5/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/c/a/call-of-duty-cover.jpg",
      price: 9500,
      descripcion: "Call of Duty: Modern Warfare es un videojuego de disparos en primera persona desarrollado por Infinity Ward y publicado por Activision. Es el decimosexto juego de la saga Call of Duty y es un reinicio de la serie Modern Warfare.​​​ Fue lanzado el 25 de octubre de 2019.",
      stock: 2,
      category: "accion",
    },
    {
      id: 3,
      title: "Gta V",
      image: "https://media.vandal.net/m/15192/grand-theft-auto-v-2015413122229_1.jpg",
      price: 5000,
      descripcion: "Grand Theft Auto V es un videojuego de acción-aventura de mundo abierto desarrollado por el estudio Rockstar North y distribuido por Rockstar Games. Fue lanzado el 17 de septiembre de 2013 para las consolas PlayStation 3 y Xbox 360.​",
      stock: 7,
      category: "accion",
    },
    {
      id: 4,
      title: "Tomb Raider",
      image: "https://store-images.s-microsoft.com/image/apps.23964.68112460555114547.f599eff6-c432-4510-af15-bfe339796812.955330ba-ec69-4007-a274-96058599d8f5",
      price: 7000,
      descripcion: "Shadow of the Tomb Raider es un videojuego de acción y aventura desarrollado por Eidos Montréal y distribuido por Square Enix, para las plataformas PlayStation 4, Xbox One y Microsoft Windows.​",
      stock: 3,
      category: "aventura",
    },
    {
      id: 5,
      title: "Far Cry 6",
      image: "https://cdn1.epicgames.com/b4565296c22549e4830c13bc7506642d/offer/TETRA_PREORDER_STANDARD%20EDITION_EPIC_Store_Portrait_1200x1600-1200x1600-ca8b802ff13813c37a44ebf68d0946a2.png",
      price: 13000,
      descripcion: "Far Cry 6 es un videojuego de disparos en primera persona desarrollado por Ubisoft Toronto y publicado por Ubisoft. Es la sexta entrega principal de la serie Far Cry, fue lanzado el 7 de octubre del 2021 para las plataformas de Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S y Google Stadia. ",
      stock: 3,
      category: "aventura",
    },
    {
      id: 6,
      title: "God Of War",
      image: "https://s3.gaming-cdn.com/images/products/7325/orig-fallback-v1/god-of-war-pc-juego-steam-cover.jpg",
      price: 9500,
      descripcion: "God of War es una serie de videojuegos hack and slash creada por SCE Santa Monica Studio y distribuida por Sony Computer Entertainment.",
      stock: 2,
      category: "aventura",
    },
    {
      id: 7,
      title: "Fifa 22",
      image: "https://img.g2a.com/323x433/1x1x0/fifa-22-pc-origin-key-europe/dce7598de0604b70ae47d576",
      price: 13900,
      descripcion: "FIFA 22 es un videojuego desarrollado por EA Vancouver y EA Romania, siendo publicado por EA Sports. Está disponible para PlayStation 4, PlayStation 5, Xbox Series X/S, Xbox One, Microsoft Windows, Google Stadia y Nintendo Switch.",
      stock: 3,
      category: "deportes",
    },
    {
      id: 8,
      title: "NBA 2K22",
      image: "https://image.api.playstation.com/vulcan/ap/rnd/202106/3002/Eaq9uyUlyLZK8L5xTlsPl0rM.png",
      price: 11000,
      descripcion: "NBA 2K22 es un videojuego de simulación de baloncesto de 2021 desarrollado por Visual Concepts y publicado por 2K Sports, basado en la National Basketball Association. Es la entrega número 23 de la franquicia NBA 2K y el sucesor de NBA 2K21.",
      stock: 3,
      category: "deportes",
    },
    {
      id: 9,
      tittle: "Madden NFL 22",
      image: "https://cdn-products.eneba.com/resized-products/3oSjLWh0PD7mPzjw-dH8E2U4LpvCc4Bh3sbfmHABsWY_350x200_1x-0.jpeg",
      price: 12700,
      descripcion: "Madden NFL 22 es un videojuego de fútbol americano basado en la National Football League, desarrollado por EA Tiburon y publicado por Electronic Arts. Es una entrega de la larga serie Madden NFL y se lanzó para Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S y Stadia.",
      stock: 3,
      category: "deportes",
    }
  ];